module Corpus02a where

test :: [String]
test =
           "every ox meanders ably" :
           "their echidna dies urgently" :
           "every fish inhales anew" :
           "their ox wins already" :
           "this ant giggles anew" :
           "every fish enquires well" :
           "every ox laughs thus" :
           "their eel dies already" :
           "one donkey eats anew" :
           "their antelope jogs slowly" :
           "every hamster adds quickly" :
           "one monkey acts quickly" :
           "this antelope acts slowly" :
           "one hamster runs easily" :
           "one monkey adds urgently" :
           "every hamster arrives thus" :
           "their eel arrives well" :
           "every dog eats well" :
           "this donkey ages frequently" :
           "this elephant ages thus" :
           "this elephant laughs anew" :
           "their eel laughs also" :
           "every dog inhales ably" :
           "their ant meanders idly" :
           "this echidna giggles idly" :
           "this elephant ages openly" :
           "one hamster jogs happily" :
           "this antelope dies quickly" :
           "this echidna laughs anew" :
           "this echidna wins urgently" :
           "their echidna giggles also" :
           "one elephant runs easily" :
           "their ant inhales also" :
           "their echidna runs easily" :
           "their eel runs already" :
           "every dog enquires idly" :
           "one antelope runs openly" :
           "every cat enquires quickly" :
           "this echidna wins frequently" :
           "every fish arrives idly" :
           []

training :: [String]
training =
           "one donkey adds quickly" :
           "this dog arrives thus" :
           "their ant wins easily" :
           "their eel enquires ably" :
           "one hamster ages happily" :
           "this echidna runs urgently" :
           "every cat enquires ably" :
           "this antelope jogs frequently" :
           "one monkey wins easily" :
           "their antelope runs frequently" :
           "every fish arrives openly" :
           "their ox giggles too" :
           "every dog observes then" :
           "one donkey jogs urgently" :
           "this antelope migrates ably" :
           "every monkey adds slowly" :
           "one donkey ages openly" :
           "their eel meanders then" :
           "this antelope jogs already" :
           "every cat ages quickly" :
           "this elephant wins already" :
           "every cat meanders idly" :
           "every fish inhales well" :
           "every dog ages slowly" :
           "their ox observes well" :
           "this elephant acts slowly" :
           "every dog meanders idly" :
           "one hamster adds too" :
           "this elephant jogs also" :
           "one donkey ages thus" :
           "their ox meanders too" :
           "this ant migrates also" :
           "their dog inhales thus" :
           "one donkey acts thus" :
           "their elephant eats slowly" :
           "every eel giggles also" :
           "every fish migrates anew" :
           "their ant arrives ably" :
           "their ox runs easily" :
           "every cat arrives happily" :
           "every donkey migrates anew" :
           "this antelope adds too" :
           "their dog enquires well" :
           "this antelope wins anew" :
           "this antelope wins urgently" :
           "their antelope wins openly" :
           "every hamster adds slowly" :
           "this eel enquires then" :
           "this elephant laughs idly" :
           "this antelope migrates also" :
           "every ox wins also" :
           "every eel migrates idly" :
           "their ant migrates already" :
           "every antelope jogs happily" :
           "every cat enquires too" :
           "one hamster inhales thus" :
           "every hamster eats frequently" :
           "every cat wins already" :
           "this elephant dies already" :
           "their ox arrives thus" :
           "their ox migrates too" :
           "one monkey eats urgently" :
           "their eel giggles then" :
           "every fish meanders also" :
           "this echidna ages too" :
           "this elephant dies well" :
           "their ant jogs also" :
           "their ant runs urgently" :
           "one hamster eats anew" :
           "their ant giggles also" :
           "one monkey inhales frequently" :
           "their ox runs already" :
           "their ant laughs easily" :
           "every fish arrives anew" :
           "this antelope inhales also" :
           "every cat arrives anew" :
           "their ox jogs then" :
           "this antelope jogs openly" :
           "this elephant runs easily" :
           "their fish inhales well" :
           "one hamster adds slowly" :
           "one monkey enquires well" :
           "this echidna ages quickly" :
           "every dog enquires quickly" :
           "one monkey jogs easily" :
           "one hamster adds then" :
           "their eel jogs idly" :
           "one dog migrates anew" :
           "every ox dies ably" :
           "this echidna meanders thus" :
           "one elephant jogs openly" :
           "every ox arrives too" :
           "every cat arrives too" :
           "every fish ages slowly" :
           "this donkey eats already" :
           "their ant observes anew" :
           "their eel observes frequently" :
           "their elephant wins urgently" :
           "their eel giggles easily" :
           "their ox laughs anew" :
           "every dog arrives anew" :
           "every ox laughs ably" :
           "every fish enquires happily" :
           "every cat adds well" :
           "one monkey adds easily" :
           "their eel eats happily" :
           "this antelope runs already" :
           "one donkey jogs ably" :
           "this antelope dies urgently" :
           "their ox laughs too" :
           "every cat migrates thus" :
           "their antelope giggles anew" :
           "this echidna giggles anew" :
           "every cat adds quickly" :
           "every hamster adds already" :
           "this antelope wins then" :
           "their eel migrates ably" :
           "one echidna giggles also" :
           "their eel meanders well" :
           "their eel meanders easily" :
           "one monkey laughs idly" :
           "their dog observes thus" :
           "their dog observes quickly" :
           "every ox acts slowly" :
           "one donkey arrives thus" :
           "one monkey arrives well" :
           "this elephant meanders also" :
           "every eel meanders anew" :
           "this echidna runs ably" :
           "every monkey adds idly" :
           "this echidna laughs also" :
           "their ox giggles ably" :
           "every ox runs already" :
           "their eel migrates idly" :
           "their ant dies already" :
           "this elephant laughs thus" :
           "this antelope dies ably" :
           "one antelope dies ably" :
           "this antelope wins slowly" :
           "this antelope runs also" :
           "every fish enquires also" :
           "every cat observes too" :
           "every dog observes thus" :
           "every donkey acts openly" :
           "their ox arrives already" :
           "every fish enquires anew" :
           "one donkey arrives ably" :
           "every dog migrates thus" :
           "every cat adds slowly" :
           "one fish adds happily" :
           "every cat migrates also" :
           "their eel laughs idly" :
           "their ox meanders ably" :
           "this antelope dies easily" :
           "every dog arrives well" :
           "every fish arrives quickly" :
           "their cat meanders idly" :
           "every fish giggles ably" :
           "their elephant dies urgently" :
           "one cat observes easily" :
           "this ant giggles then" :
           "every ox meanders openly" :
           "this elephant laughs ably" :
           "this elephant giggles urgently" :
           "every dog runs urgently" :
           "this ant giggles quickly" :
           "one elephant runs urgently" :
           "their eel giggles anew" :
           "every ant migrates then" :
           "one antelope dies urgently" :
           "every ant giggles ably" :
           "every dog observes happily" :
           "this echidna eats openly" :
           "every hamster eats openly" :
           "this echidna giggles also" :
           "one fish enquires anew" :
           "every dog arrives quickly" :
           "their antelope acts slowly" :
           "this donkey acts slowly" :
           "their ant meanders well" :
           "their cat observes well" :
           "their eel laughs ably" :
           "every donkey acts slowly" :
           "one hamster enquires thus" :
           "this elephant runs already" :
           "one monkey runs openly" :
           "one hamster arrives then" :
           "every dog adds slowly" :
           "one donkey adds then" :
           "one hamster adds quickly" :
           "this echidna observes thus" :
           "every cat enquires slowly" :
           "one hamster observes too" :
           "their ant enquires then" :
           "their eel arrives thus" :
           "every fish arrives then" :
           "their cat inhales well" :
           "every cat observes ably" :
           "every cat meanders also" :
           "this antelope adds frequently" :
           "one monkey adds happily" :
           "this eel giggles openly" :
           "every dog enquires slowly" :
           "one donkey eats slowly" :
           "every dog arrives idly" :
           "every dog inhales frequently" :
           "one dog arrives too" :
           "every monkey ages slowly" :
           "every dog arrives thus" :
           "their fish inhales also" :
           "one cat observes quickly" :
           "their eel migrates then" :
           "every donkey adds then" :
           "one donkey acts well" :
           "their fish observes then" :
           "this ant meanders too" :
           "one monkey runs ably" :
           "every cat wins openly" :
           "this antelope jogs anew" :
           "their eel giggles urgently" :
           "their ox giggles thus" :
           "their antelope meanders also" :
           "their eel observes well" :
           "every fish enquires idly" :
           "their antelope dies already" :
           "every monkey acts well" :
           "one monkey arrives then" :
           "this antelope giggles idly" :
           "their ant meanders too" :
           "every ox giggles also" :
           "one hamster acts well" :
           "one echidna wins anew" :
           "every eel laughs also" :
           "their ant laughs then" :
           "every fish eats ably" :
           "this donkey eats happily" :
           "their eel meanders too" :
           "every fish adds happily" :
           "their fish arrives too" :
           "their ox dies easily" :
           "their dog inhales too" :
           "one cat enquires too" :
           "this echidna wins ably" :
           "their dog inhales happily" :
           "this echidna runs too" :
           "this antelope jogs urgently" :
           "their antelope wins urgently" :
           "this elephant migrates well" :
           "every hamster jogs urgently" :
           "their dog observes then" :
           "every dog observes quickly" :
           "their antelope ages happily" :
           "this elephant laughs openly" :
           "their antelope wins already" :
           "every eel laughs anew" :
           "their ant migrates ably" :
           "every fish meanders anew" :
           "one fish observes slowly" :
           "one hamster wins urgently" :
           "their ant meanders also" :
           "every donkey eats quickly" :
           "this elephant jogs then" :
           "one echidna wins openly" :
           "this elephant jogs happily" :
           "one donkey dies also" :
           "every cat eats happily" :
           "one hamster ages slowly" :
           "one cat enquires thus" :
           "their ant meanders then" :
           "every ox giggles idly" :
           "their echidna runs already" :
           "their ant migrates thus" :
           "their ant laughs well" :
           "every fish migrates idly" :
           "this donkey ages quickly" :
           "every dog inhales well" :
           "every hamster eats well" :
           "one hamster ages urgently" :
           "their ant meanders thus" :
           "their fish giggles well" :
           "one dog inhales thus" :
           "their cat enquires slowly" :
           "every ant laughs ably" :
           "one donkey ages then" :
           "one monkey adds quickly" :
           "one fish enquires then" :
           "one dog giggles also" :
           "every dog inhales then" :
           "every cat migrates idly" :
           "one donkey adds openly" :
           "this eel migrates also" :
           "one cat laughs anew" :
           "their ant giggles anew" :
           "their elephant runs openly" :
           "every cat inhales already" :
           "every cat observes frequently" :
           "this elephant inhales then" :
           "this ant dies also" :
           "their ox observes too" :
           "their ox migrates ably" :
           "every ant wins openly" :
           "one cat arrives thus" :
           "this antelope eats thus" :
           "one fish inhales too" :
           "their dog inhales idly" :
           "their cat arrives too" :
           "one echidna wins easily" :
           "one cat inhales slowly" :
           "this ant runs urgently" :
           "this antelope giggles anew" :
           "one hamster ages frequently" :
           "this echidna runs easily" :
           "their antelope dies easily" :
           "one donkey dies already" :
           "this echidna dies frequently" :
           "their ox jogs already" :
           "one donkey ages quickly" :
           "every cat inhales too" :
           "every cat observes slowly" :
           "this donkey adds slowly" :
           "this antelope runs slowly" :
           "one hamster adds frequently" :
           "their eel inhales thus" :
           "one monkey ages slowly" :
           "every dog arrives slowly" :
           "their ant observes frequently" :
           "one monkey eats slowly" :
           "their ox giggles also" :
           "this elephant dies quickly" :
           "every dog observes slowly" :
           "their ox meanders idly" :
           "their dog ages well" :
           "every elephant wins already" :
           "every cat eats slowly" :
           "this eel migrates idly" :
           "one echidna dies easily" :
           "their ant migrates urgently" :
           "one echidna dies idly" :
           "this antelope dies already" :
           "one fish arrives thus" :
           "one dog wins anew" :
           "this antelope arrives then" :
           "their eel laughs anew" :
           "their ant inhales then" :
           "one hamster enquires slowly" :
           "every monkey eats happily" :
           "their ant migrates slowly" :
           "one monkey arrives too" :
           "their echidna migrates idly" :
           "this elephant dies urgently" :
           "every dog migrates openly" :
           "this echidna jogs already" :
           "every monkey ages quickly" :
           "their ox laughs then" :
           "their eel laughs slowly" :
           "one monkey adds frequently" :
           "every dog arrives ably" :
           "every cat migrates anew" :
           "one elephant runs openly" :
           "this elephant arrives thus" :
           "one hamster dies quickly" :
           "every donkey ages quickly" :
           "their cat enquires ably" :
           "this donkey jogs already" :
           "their ant inhales thus" :
           "this elephant eats quickly" :
           "every monkey observes then" :
           "their ox wins anew" :
           "this ant meanders anew" :
           "every fish inhales then" :
           "their ant laughs openly" :
           "one echidna jogs easily" :
           "every dog ages frequently" :
           "one donkey observes thus" :
           "one cat arrives happily" :
           "their fish enquires thus" :
           "this elephant eats frequently" :
           "their ox dies slowly" :
           "this echidna dies slowly" :
           "one donkey acts quickly" :
           "their ox meanders anew" :
           "every cat giggles also" :
           "one donkey ages slowly" :
           "every ox inhales then" :
           "every monkey inhales well" :
           "every donkey runs easily" :
           "this eel giggles ably" :
           "every fish adds thus" :
           "this eel laughs anew" :
           "one hamster enquires too" :
           "every eel observes well" :
           "one hamster jogs already" :
           "one donkey jogs openly" :
           "their ox meanders urgently" :
           "this elephant runs quickly" :
           "every ox arrives then" :
           "every elephant runs anew" :
           "one dog arrives well" :
           "one monkey observes then" :
           "this elephant acts quickly" :
           "their ox giggles urgently" :
           "every dog observes well" :
           "every fish inhales ably" :
           "their elephant eats easily" :
           "every dog observes ably" :
           "every ant enquires well" :
           "their dog arrives then" :
           "their eel inhales too" :
           "every ant meanders then" :
           "this eel laughs thus" :
           "every donkey ages openly" :
           "one cat arrives idly" :
           "one hamster observes slowly" :
           "this antelope wins openly" :
           "one hamster enquires then" :
           "their cat arrives thus" :
           "every fish observes too" :
           "their ant meanders ably" :
           "every monkey adds too" :
           "every hamster jogs also" :
           "their cat inhales then" :
           "this donkey adds happily" :
           "their ant giggles already" :
           "one monkey adds then" :
           "every ant giggles idly" :
           "one hamster eats thus" :
           "this eel observes frequently" :
           "one echidna acts frequently" :
           "one hamster runs openly" :
           "one elephant wins urgently" :
           "this antelope eats slowly" :
           "every monkey adds frequently" :
           "every dog giggles idly" :
           "their ox meanders then" :
           "this antelope eats easily" :
           "their echidna laughs idly" :
           "this ant laughs anew" :
           "this elephant jogs already" :
           "one monkey runs urgently" :
           "this donkey eats well" :
           "one monkey meanders idly" :
           "every fish arrives easily" :
           "this elephant adds happily" :
           "this echidna dies already" :
           "one hamster ages ably" :
           "one monkey adds already" :
           "every dog arrives frequently" :
           "this elephant giggles ably" :
           "their ox migrates well" :
           "this donkey ages then" :
           "every echidna dies urgently" :
           "every cat observes anew" :
           "this echidna eats well" :
           "one ox migrates also" :
           "one donkey adds urgently" :
           "this antelope meanders idly" :
           "one donkey wins quickly" :
           "their ant giggles urgently" :
           "every cat arrives slowly" :
           "this echidna wins easily" :
           "one elephant eats frequently" :
           "every eel observes then" :
           "every cat arrives ably" :
           "one hamster eats urgently" :
           "one monkey acts ably" :
           "every ant migrates easily" :
           "their ant migrates then" :
           "their ant inhales slowly" :
           "one elephant dies frequently" :
           "this echidna eats frequently" :
           "their ox inhales well" :
           "this echidna jogs slowly" :
           "their elephant dies also" :
           "every hamster eats slowly" :
           "this antelope laughs idly" :
           "their eel wins urgently" :
           "every ant meanders well" :
           "one fish observes then" :
           "this dog observes well" :
           "their dog enquires then" :
           "this elephant runs frequently" :
           "their eel enquires thus" :
           "one donkey adds slowly" :
           "every cat ages urgently" :
           "this elephant wins also" :
           "their echidna runs happily" :
           "their fish arrives thus" :
           "this echidna jogs idly" :
           "one elephant dies openly" :
           "their ox migrates then" :
           "their fish observes thus" :
           "one elephant dies idly" :
           "one donkey migrates idly" :
           "one dog inhales well" :
           "their antelope runs already" :
           "every eel migrates ably" :
           "every fish enquires quickly" :
           "this antelope giggles ably" :
           "this elephant giggles anew" :
           "their echidna jogs easily" :
           "this antelope eats well" :
           "their elephant wins openly" :
           "one echidna acts quickly" :
           "this ant migrates anew" :
           "every elephant runs easily" :
           "this eel laughs well" :
           "this elephant jogs slowly" :
           "their ant jogs urgently" :
           "this cat enquires well" :
           "their ox dies already" :
           "their ant giggles too" :
           "one antelope runs easily" :
           "their cat enquires well" :
           "one dog arrives thus" :
           "every ant migrates ably" :
           "one donkey inhales then" :
           "every donkey inhales well" :
           "this echidna adds slowly" :
           "every fish adds quickly" :
           "every dog migrates idly" :
           "their ant laughs ably" :
           "one antelope jogs already" :
           "every dog runs easily" :
           "this antelope giggles slowly" :
           "this echidna jogs frequently" :
           "their eel giggles also" :
           "every echidna runs urgently" :
           "one donkey adds well" :
           "one donkey runs already" :
           "every cat arrives well" :
           "one hamster ages then" :
           "every dog acts openly" :
           "every monkey acts happily" :
           "their ant enquires also" :
           "every fish arrives too" :
           "their dog enquires too" :
           "their antelope runs quickly" :
           "this antelope meanders openly" :
           "their cat enquires thus" :
           "every ox migrates ably" :
           "their dog inhales then" :
           "this elephant adds slowly" :
           "every cat inhales slowly" :
           "every eel inhales too" :
           "this elephant jogs frequently" :
           "one donkey runs frequently" :
           "one monkey arrives thus" :
           "this elephant acts happily" :
           "this echidna migrates also" :
           "this antelope wins also" :
           "every fish arrives already" :
           "one hamster ages too" :
           "one hamster dies already" :
           "every donkey runs openly" :
           "this ant arrives slowly" :
           "every fish acts slowly" :
           "one monkey acts slowly" :
           "one monkey runs already" :
           "one elephant jogs frequently" :
           "one eel migrates ably" :
           "this echidna giggles well" :
           "one donkey wins easily" :
           "this antelope meanders ably" :
           "every cat ages slowly" :
           "one dog enquires well" :
           "this echidna dies also" :
           "their antelope eats easily" :
           "one eel giggles idly" :
           "every dog meanders also" :
           "every monkey adds happily" :
           "one antelope wins ably" :
           "their ant migrates idly" :
           "one cat migrates anew" :
           "every dog laughs already" :
           "every cat inhales quickly" :
           "their ant giggles thus" :
           "this echidna jogs openly" :
           "one hamster ages already" :
           "their eel runs openly" :
           "this eel meanders openly" :
           "every hamster ages frequently" :
           "their ox laughs urgently" :
           "this antelope acts frequently" :
           "this antelope laughs also" :
           "this echidna runs already" :
           "every fish laughs idly" :
           "one cat observes too" :
           "their eel jogs openly" :
           "one antelope runs anew" :
           "this elephant acts frequently" :
           "one eel migrates idly" :
           "their elephant wins already" :
           "their ox jogs easily" :
           "every monkey ages frequently" :
           "this donkey inhales thus" :
           "their ant inhales too" :
           "this echidna jogs ably" :
           "every dog arrives then" :
           "every donkey eats frequently" :
           "this antelope enquires thus" :
           "every hamster ages already" :
           "their eel runs easily" :
           "one dog adds quickly" :
           "every fish giggles then" :
           "every fish meanders idly" :
           "one hamster ages anew" :
           "every dog observes also" :
           "every dog adds too" :
           "one echidna migrates also" :
           "every eel runs easily" :
           "their eel dies slowly" :
           "every cat laughs anew" :
           "one ant meanders thus" :
           "one ox meanders also" :
           "one elephant meanders idly" :
           "one donkey enquires then" :
           "one monkey ages easily" :
           "every hamster acts quickly" :
           "one hamster adds well" :
           "every donkey enquires too" :
           "one hamster eats openly" :
           "one echidna dies also" :
           "their ox meanders openly" :
           "one elephant dies urgently" :
           "one hamster enquires ably" :
           "one dog acts frequently" :
           "this eel observes then" :
           "this elephant laughs already" :
           "one echidna jogs already" :
           "every fish meanders thus" :
           "their eel laughs already" :
           "one hamster ages thus" :
           "every ant meanders urgently" :
           "one donkey jogs frequently" :
           "one eel giggles also" :
           "one antelope runs also" :
           "this antelope eats happily" :
           "their ox enquires too" :
           "their eel giggles already" :
           "every cat eats quickly" :
           "every ox migrates anew" :
           "every dog laughs then" :
           "one hamster adds happily" :
           "one donkey observes slowly" :
           "every donkey inhales ably" :
           "this ant giggles too" :
           "every eel wins urgently" :
           "their antelope giggles idly" :
           "one donkey giggles quickly" :
           "every monkey wins ably" :
           "one antelope wins easily" :
           "this echidna wins slowly" :
           "this antelope jogs also" :
           "one hamster observes then" :
           "every cat inhales happily" :
           "one donkey acts frequently" :
           "every cat migrates well" :
           "every ox laughs idly" :
           "their ant laughs anew" :
           "every eel migrates anew" :
           "one elephant jogs easily" :
           "every eel dies anew" :
           "their antelope wins ably" :
           "their ox enquires quickly" :
           "their antelope eats frequently" :
           "their eel wins happily" :
           "one hamster observes already" :
           "this antelope ages quickly" :
           "every cat giggles too" :
           "their ant meanders already" :
           "one monkey acts easily" :
           "every monkey acts frequently" :
           "one dog acts openly" :
           "their ox inhales then" :
           "their fish meanders ably" :
           "their antelope jogs frequently" :
           "one echidna dies urgently" :
           "every fish enquires thus" :
           "every cat inhales also" :
           "one fish arrives urgently" :
           "this echidna wins already" :
           "every cat arrives frequently" :
           "one donkey runs urgently" :
           "every dog jogs frequently" :
           "their ant laughs thus" :
           "one donkey acts easily" :
           "every fish adds slowly" :
           "this ant giggles ably" :
           "one hamster acts quickly" :
           "every donkey acts quickly" :
           "this ant laughs idly" :
           "one monkey dies openly" :
           "one donkey ages easily" :
           "one donkey jogs already" :
           "their ox wins quickly" :
           "one fish observes too" :
           "every fish runs openly" :
           "their ant observes well" :
           "every eel meanders ably" :
           "one cat adds too" :
           "every ant jogs already" :
           "their elephant jogs urgently" :
           "this echidna runs quickly" :
           "one cat inhales well" :
           "this eel meanders idly" :
           "this elephant meanders anew" :
           "their dog eats slowly" :
           "this elephant ages frequently" :
           "one donkey acts then" :
           "their cat observes too" :
           "one monkey eats then" :
           "every cat observes quickly" :
           "every donkey adds slowly" :
           "every ant observes then" :
           "every donkey acts frequently" :
           "every fish observes ably" :
           "one fish arrives then" :
           "their elephant giggles quickly" :
           "their ant inhales well" :
           "one monkey acts frequently" :
           "one hamster runs happily" :
           "one hamster inhales slowly" :
           "every fish acts too" :
           "every ox giggles urgently" :
           "every dog ages happily" :
           "one donkey eats thus" :
           "this antelope dies anew" :
           "one elephant jogs urgently" :
           "their ant wins urgently" :
           "every cat ages then" :
           "their ant runs already" :
           "this echidna jogs urgently" :
           "their antelope observes anew" :
           "their fish arrives well" :
           "one monkey adds thus" :
           "their dog meanders ably" :
           "every fish adds then" :
           "their echidna meanders anew" :
           "this antelope dies slowly" :
           "every fish eats quickly" :
           "every cat observes well" :
           "their antelope dies openly" :
           "their ox migrates idly" :
           "one donkey adds already" :
           "their eel giggles thus" :
           "one donkey runs openly" :
           "every monkey adds quickly" :
           "one hamster acts happily" :
           "this ant migrates ably" :
           "their echidna runs then" :
           "this antelope eats quickly" :
           "one antelope dies already" :
           "one donkey acts too" :
           "every cat giggles thus" :
           "one donkey wins urgently" :
           "every donkey ages slowly" :
           "every fish meanders too" :
           "this echidna giggles ably" :
           "one monkey acts thus" :
           "every fish meanders urgently" :
           "their ox giggles openly" :
           "their cat acts slowly" :
           "their antelope runs urgently" :
           "every cat arrives thus" :
           "one hamster arrives too" :
           "their elephant wins easily" :
           "one elephant runs already" :
           "every fish enquires then" :
           "every ant giggles also" :
           "their eel jogs well" :
           "their eel giggles frequently" :
           "this echidna ages easily" :
           "this echidna inhales then" :
           "one cat enquires then" :
           "every fish arrives also" :
           "one donkey wins anew" :
           "every monkey jogs idly" :
           "this antelope acts then" :
           "this ant meanders idly" :
           "this eel giggles too" :
           "every fish migrates ably" :
           "every donkey meanders also" :
           "this echidna dies anew" :
           "their ant laughs idly" :
           "every fish observes then" :
           "one donkey acts slowly" :
           "their ox migrates easily" :
           "their dog arrives idly" :
           "this elephant giggles thus" :
           "every fish observes well" :
           "one antelope wins anew" :
           "every hamster acts urgently" :
           "their eel migrates frequently" :
           "every eel enquires anew" :
           "one cat observes well" :
           "their ox meanders thus" :
           "every fish dies already" :
           "every dog enquires anew" :
           "every eel migrates urgently" :
           "one hamster runs also" :
           "their hamster inhales idly" :
           "one fish enquires already" :
           "this antelope runs anew" :
           "this elephant dies happily" :
           "one monkey ages then" :
           "every dog migrates also" :
           "every hamster adds happily" :
           "one donkey adds thus" :
           "one dog inhales then" :
           "one donkey acts openly" :
           "their eel jogs anew" :
           "this ant meanders easily" :
           "this eel observes thus" :
           "one monkey observes thus" :
           "one hamster acts frequently" :
           "one echidna runs urgently" :
           "one donkey enquires thus" :
           "every eel laughs idly" :
           "their eel dies urgently" :
           "one dog observes well" :
           "their ox laughs well" :
           "one monkey ages well" :
           "every dog jogs easily" :
           "this echidna enquires thus" :
           "their ant migrates easily" :
           "this ant migrates already" :
           "one monkey ages too" :
           "every fish arrives thus" :
           "this echidna adds frequently" :
           "their elephant ages quickly" :
           "this elephant eats already" :
           "this antelope acts well" :
           "their ox laughs idly" :
           "this elephant jogs anew" :
           "every cat enquires then" :
           "every eel jogs already" :
           "one donkey adds too" :
           "their ox laughs easily" :
           "their fish enquires too" :
           "every ant giggles anew" :
           "one ox meanders well" :
           "every hamster ages slowly" :
           "this echidna wins openly" :
           "this antelope adds urgently" :
           "one antelope wins already" :
           "one donkey eats already" :
           "every antelope runs already" :
           "every cat inhales anew" :
           "every fish meanders well" :
           "their cat laughs thus" :
           "one donkey acts urgently" :
           "this antelope runs happily" :
           "this eel laughs also" :
           "one hamster eats slowly" :
           "this elephant meanders idly" :
           "this antelope jogs slowly" :
           "every cat observes then" :
           "every hamster ages easily" :
           "this ant inhales then" :
           "one donkey dies urgently" :
           "one donkey acts ably" :
           "one hamster eats frequently" :
           "this echidna meanders anew" :
           "every monkey acts thus" :
           "every donkey adds frequently" :
           "every ant giggles openly" :
           "their eel runs urgently" :
           "every dog arrives also" :
           "every echidna adds happily" :
           "every dog observes too" :
           "this echidna acts frequently" :
           "one donkey ages frequently" :
           "every monkey eats frequently" :
           "this antelope migrates idly" :
           "this ant inhales happily" :
           "every fish observes happily" :
           "this echidna giggles frequently" :
           "this antelope adds already" :
           "one donkey acts happily" :
           "one donkey observes well" :
           "every cat ages frequently" :
           "this antelope jogs idly" :
           "this eel laughs idly" :
           "one donkey inhales too" :
           "this antelope arrives easily" :
           "their ant laughs also" :
           "their fish enquires anew" :
           "one monkey observes well" :
           "their ant runs easily" :
           "their ant enquires too" :
           "their cat enquires then" :
           "their fish enquires also" :
           "every ant observes thus" :
           "one echidna jogs openly" :
           "one donkey wins happily" :
           "their ox observes thus" :
           "one echidna dies openly" :
           "their eel giggles well" :
           "one elephant wins openly" :
           "every dog migrates easily" :
           "this elephant dies also" :
           "every dog laughs anew" :
           "every dog inhales happily" :
           "their fish observes too" :
           "their ant laughs urgently" :
           "every fish giggles also" :
           "this antelope wins ably" :
           "every cat arrives quickly" :
           "their eel inhales well" :
           "their eel arrives then" :
           "one monkey runs also" :
           "every dog observes frequently" :
           "their echidna dies easily" :
           "one fish observes well" :
           "every cat acts happily" :
           "one fish enquires also" :
           "their dog observes anew" :
           "this elephant jogs idly" :
           "one monkey dies urgently" :
           "every cat inhales thus" :
           "one dog meanders ably" :
           "one monkey observes too" :
           "their fish inhales ably" :
           "every cat laughs also" :
           "every cat eats urgently" :
           "every fish giggles idly" :
           "their ant runs openly" :
           "every hamster ages happily" :
           "one monkey ages quickly" :
           "every hamster observes too" :
           "one ant giggles also" :
           "this ant ages frequently" :
           "their elephant acts quickly" :
           "their ant arrives thus" :
           "their cat inhales thus" :
           "every dog inhales too" :
           "this donkey acts openly" :
           "every dog acts frequently" :
           "their elephant jogs anew" :
           "every fish acts quickly" :
           "their ox migrates also" :
           "every fish ages urgently" :
           "their eel wins already" :
           "this donkey adds quickly" :
           "one donkey enquires well" :
           "their ox laughs thus" :
           "this elephant eats slowly" :
           "every fish migrates also" :
           "this antelope runs ably" :
           "one hamster acts easily" :
           "their eel observes too" :
           "their ant dies openly" :
           "their eel migrates openly" :
           "one cat observes ably" :
           "every fish adds frequently" :
           "this eel jogs already" :
           "their echidna wins idly" :
           "one hamster arrives well" :
           "one elephant jogs already" :
           "one donkey eats frequently" :
           "this elephant dies openly" :
           "this echidna jogs easily" :
           "this antelope meanders anew" :
           "one ox migrates ably" :
           "this elephant wins ably" :
           "their eel migrates well" :
           "every ox migrates idly" :
           "their ox jogs openly" :
           "their dog migrates also" :
           "every cat runs easily" :
           "their ox jogs slowly" :
           "one donkey adds happily" :
           "this echidna jogs happily" :
           "every ant laughs idly" :
           "one donkey ages happily" :
           "one fish observes ably" :
           "one monkey ages frequently" :
           "their ox arrives well" :
           "every dog enquires also" :
           "every fish laughs also" :
           "every eel laughs well" :
           "one cat acts quickly" :
           "one cat inhales too" :
           "every cat arrives then" :
           "every ox meanders idly" :
           "this echidna migrates anew" :
           "one cat arrives too" :
           "every fish enquires frequently" :
           "one hamster eats quickly" :
           "one monkey jogs openly" :
           "their ant migrates anew" :
           "one hamster wins openly" :
           "their ox laughs already" :
           "their eel arrives too" :
           "one echidna dies anew" :
           "this elephant runs urgently" :
           "this ant wins easily" :
           "their ox migrates thus" :
           "this echidna eats happily" :
           "this eel migrates ably" :
           "their eel migrates anew" :
           "every dog meanders thus" :
           "this ant giggles idly" :
           "this eel migrates anew" :
           "every fish inhales slowly" :
           "their echidna adds too" :
           "one antelope jogs easily" :
           "one hamster dies ably" :
           "this antelope observes idly" :
           "their eel laughs easily" :
           "this eel meanders ably" :
           "one donkey arrives too" :
           "their elephant runs already" :
           "every cat meanders happily" :
           "this ant giggles thus" :
           "every dog inhales slowly" :
           "every ox laughs anew" :
           "this ant meanders also" :
           "their donkey ages well" :
           "every fish observes slowly" :
           "every fish giggles easily" :
           "their ox migrates openly" :
           "one antelope giggles anew" :
           "their ant giggles ably" :
           "every eel giggles idly" :
           "this eel meanders also" :
           "every cat acts already" :
           "one cat inhales then" :
           "one monkey eats easily" :
           "one fish jogs openly" :
           "every hamster acts happily" :
           "this antelope acts quickly" :
           "their ant giggles easily" :
           "one monkey ages happily" :
           "their eel meanders also" :
           "one monkey inhales too" :
           "one hamster eats well" :
           "their dog enquires anew" :
           "their ox dies urgently" :
           "every fish arrives well" :
           "this antelope wins quickly" :
           "their ox runs openly" :
           "one antelope ages happily" :
           "their echidna wins already" :
           "one hamster ages easily" :
           "this elephant migrates anew" :
           "their ox giggles anew" :
           "one hamster runs slowly" :
           "their monkey ages happily" :
           "every ox laughs easily" :
           "their eel laughs thus" :
           "their fish arrives also" :
           "this antelope dies openly" :
           "their ox meanders also" :
           "every dog jogs slowly" :
           "their ox wins happily" :
           "this echidna meanders ably" :
           "this echidna inhales thus" :
           "one donkey ages urgently" :
           "one echidna laughs already" :
           "this eel runs slowly" :
           "every dog adds frequently" :
           "every eel meanders also" :
           "this elephant dies idly" :
           "every eel meanders easily" :
           "their ant laughs too" :
           "this ant laughs ably" :
           "one hamster eats happily" :
           "this donkey laughs then" :
           "one echidna runs idly" :
           "one monkey acts too" :
           "their ox giggles idly" :
           "one fish enquires thus" :
           "every ox meanders also" :
           "one hamster jogs urgently" :
           "one hamster arrives idly" :
           "one monkey eats happily" :
           "every cat observes thus" :
           "every monkey wins easily" :
           "this antelope jogs happily" :
           "this eel giggles also" :
           "every fish laughs ably" :
           "one monkey jogs urgently" :
           "their ox runs urgently" :
           "one hamster dies openly" :
           "every dog laughs idly" :
           "this antelope laughs ably" :
           "their elephant jogs already" :
           "their ox enquires thus" :
           "their ox migrates urgently" :
           "one antelope giggles idly" :
           "this echidna laughs openly" :
           "one donkey eats quickly" :
           "every cat ages happily" :
           "every fish inhales frequently" :
           "their dog meanders also" :
           "every fish meanders ably" :
           "their echidna dies openly" :
           "one cat enquires anew" :
           "this antelope runs openly" :
           "their echidna runs anew" :
           "every ox giggles ably" :
           "one cat enquires slowly" :
           "one monkey eats quickly" :
           "one antelope runs already" :
           "every fish laughs too" :
           "one monkey wins openly" :
           "one monkey ages openly" :
           "every dog meanders well" :
           "their cat giggles also" :
           "every fish ages happily" :
           "one antelope wins urgently" :
           "every eel giggles anew" :
           "this ant migrates thus" :
           "their dog enquires ably" :
           "this echidna laughs idly" :
           "one monkey inhales ably" :
           "every ant giggles urgently" :
           "every ox meanders anew" :
           "every cat eats already" :
           "this antelope runs urgently" :
           "every cat giggles idly" :
           "their hamster ages slowly" :
           "their echidna dies already" :
           "their eel jogs already" :
           "this elephant ages urgently" :
           "every dog migrates too" :
           "their monkey wins also" :
           "every cat inhales then" :
           "this elephant eats happily" :
           "their echidna runs quickly" :
           "one donkey inhales well" :
           "their eel enquires too" :
           "their elephant jogs openly" :
           "their ox meanders already" :
           "every fish acts then" :
           "their ox jogs anew" :
           "their echidna jogs urgently" :
           "their ox wins openly" :
           "this elephant wins urgently" :
           "one donkey eats easily" :
           "every hamster ages thus" :
           "one hamster adds thus" :
           "one hamster arrives easily" :
           "this elephant giggles easily" :
           "every fish inhales too" :
           "one echidna runs openly" :
           "this antelope migrates anew" :
           "this antelope adds easily" :
           "every dog adds happily" :
           "this donkey ages urgently" :
           "their eel meanders ably" :
           "this eel laughs ably" :
           "their ox meanders happily" :
           "their eel wins easily" :
           "this antelope adds happily" :
           "one monkey laughs also" :
           "every ant migrates openly" :
           "one fish arrives well" :
           "one dog arrives happily" :
           "every dog acts slowly" :
           "their fish giggles ably" :
           "every donkey adds well" :
           "their eel migrates thus" :
           "this antelope giggles also" :
           "every donkey adds quickly" :
           "every donkey wins urgently" :
           "this echidna dies idly" :
           "their ox enquires then" :
           "one monkey giggles ably" :
           "one donkey wins openly" :
           "one dog enquires urgently" :
           "every cat inhales openly" :
           "one cat arrives well" :
           "their fish observes well" :
           "every dog eats slowly" :
           "their ant giggles then" :
           "this echidna dies urgently" :
           "one monkey wins already" :
           "their ox acts well" :
           "one antelope runs quickly" :
           "every fish eats frequently" :
           "every ant laughs also" :
           "their cat eats slowly" :
           "one monkey dies already" :
           "this eel runs easily" :
           "every fish ages easily" :
           "every monkey adds urgently" :
           "their eel migrates easily" :
           "one hamster runs already" :
           "every cat migrates ably" :
           "their ox laughs also" :
           "one cat arrives anew" :
           "their eel dies openly" :
           "this echidna meanders already" :
           "their eel inhales then" :
           "their elephant dies frequently" :
           "every monkey eats quickly" :
           "every hamster acts frequently" :
           "one hamster adds openly" :
           "this echidna runs also" :
           "one cat runs urgently" :
           "one donkey enquires idly" :
           "every dog laughs ably" :
           "one monkey acts openly" :
           "their eel laughs urgently" :
           "every cat giggles ably" :
           "one echidna giggles idly" :
           "their antelope runs easily" :
           "their ox giggles then" :
           "one donkey dies openly" :
           "their ant meanders easily" :
           "their fish arrives then" :
           "one hamster dies anew" :
           "one hamster eats already" :
           "this ant meanders ably" :
           "one donkey acts already" :
           "their ox migrates anew" :
           "this donkey acts happily" :
           "one donkey adds frequently" :
           "their ant ages happily" :
           "every dog adds urgently" :
           "this antelope ages happily" :
           "this donkey eats slowly" :
           "their eel laughs too" :
           "this echidna dies easily" :
           "every eel dies quickly" :
           "their echidna giggles anew" :
           "every cat laughs ably" :
           "their eel giggles too" :
           "every hamster eats happily" :
           "this echidna inhales too" :
           "their monkey adds frequently" :
           "one monkey enquires quickly" :
           "every hamster adds too" :
           "one monkey observes also" :
           "one donkey eats happily" :
           "one monkey ages thus" :
           "one monkey inhales thus" :
           "their ant inhales idly" :
           "one donkey jogs easily" :
           "their elephant adds happily" :
           "one hamster enquires well" :
           "one monkey jogs ably" :
           "one dog arrives then" :
           "this ant giggles also" :
           "every dog enquires too" :
           "one monkey eats openly" :
           "this ant migrates idly" :
           "every ant meanders ably" :
           []
