module Corpus02b where

test :: [String]
test =
           "one cat acts urgently" :
           "every donkey acts also" :
           "one ant dies happily" :
           "every donkey jogs thus" :
           "every donkey laughs happily" :
           "every hamster giggles already" :
           "every monkey runs openly" :
           "every echidna jogs then" :
           "every donkey adds well" :
           "one antelope arrives well" :
           "one antelope arrives easily" :
           "one antelope acts openly" :
           "every eel migrates slowly" :
           "one antelope inhales happily" :
           "every monkey runs also" :
           "every ant enquires openly" :
           "one ant wins ably" :
           "every hamster arrives slowly" :
           "one antelope migrates happily" :
           "every dog dies ably" :
           "every antelope inhales ably" :
           "every ox runs anew" :
           "every antelope wins anew" :
           "every eel eats anew" :
           "every cat laughs quickly" :
           "every donkey acts anew" :
           "every echidna giggles ably" :
           "one antelope migrates idly" :
           "every cat enquires also" :
           "every elephant giggles happily" :
           "every monkey acts too" :
           "every cat eats urgently" :
           "one cat adds already" :
           "one antelope arrives ably" :
           "every ant ages then" :
           "every ant dies idly" :
           "every monkey runs slowly" :
           "every elephant eats slowly" :
           "one antelope arrives quickly" :
           "every elephant adds also" :
           []

training :: [String]
training =
           "every antelope giggles easily" :
           "every echidna jogs ably" :
           "every echidna acts anew" :
           "every antelope dies quickly" :
           "every donkey acts then" :
           "every hamster wins urgently" :
           "every dog eats too" :
           "every fish ages happily" :
           "every ant enquires frequently" :
           "every echidna jogs urgently" :
           "every ant acts happily" :
           "every monkey arrives ably" :
           "every dog wins thus" :
           "every eel acts frequently" :
           "every cat observes idly" :
           "every hamster jogs frequently" :
           "every cat acts happily" :
           "every echidna jogs easily" :
           "every cat enquires already" :
           "one ant ages urgently" :
           "every eel migrates also" :
           "every cat laughs already" :
           "one ant migrates too" :
           "every dog dies slowly" :
           "every antelope adds also" :
           "one antelope laughs idly" :
           "every donkey observes idly" :
           "every donkey adds idly" :
           "every ant runs well" :
           "every ant enquires easily" :
           "every elephant eats too" :
           "every echidna eats idly" :
           "every fish migrates frequently" :
           "every ox giggles thus" :
           "every donkey arrives also" :
           "one cat dies slowly" :
           "every elephant runs then" :
           "one antelope migrates quickly" :
           "every eel laughs already" :
           "every dog adds openly" :
           "one antelope observes also" :
           "every echidna arrives then" :
           "every ant adds well" :
           "every ant giggles slowly" :
           "every donkey inhales idly" :
           "one cat runs then" :
           "one antelope ages also" :
           "one antelope eats also" :
           "every echidna eats ably" :
           "every fish adds already" :
           "every eel migrates thus" :
           "every ant acts quickly" :
           "one ant wins anew" :
           "every antelope runs then" :
           "every cat jogs well" :
           "every dog arrives ably" :
           "every dog migrates frequently" :
           "every donkey meanders quickly" :
           "every donkey migrates quickly" :
           "one ant meanders happily" :
           "one ant adds easily" :
           "every ant meanders happily" :
           "every fish migrates openly" :
           "every eel ages slowly" :
           "one ant migrates already" :
           "every monkey acts anew" :
           "every cat ages idly" :
           "every elephant runs anew" :
           "every elephant jogs quickly" :
           "every hamster adds anew" :
           "every echidna meanders already" :
           "every echidna eats then" :
           "every donkey acts happily" :
           "every elephant giggles urgently" :
           "every fish wins also" :
           "one ant giggles ably" :
           "every ant jogs anew" :
           "every ant giggles ably" :
           "every ox arrives easily" :
           "every eel observes also" :
           "one ant meanders idly" :
           "one ant arrives anew" :
           "every elephant migrates anew" :
           "every ox inhales quickly" :
           "one antelope giggles thus" :
           "every hamster jogs then" :
           "every antelope laughs well" :
           "every antelope laughs openly" :
           "every eel observes idly" :
           "one ant laughs slowly" :
           "every ox wins anew" :
           "every hamster jogs ably" :
           "every ant acts anew" :
           "every cat observes slowly" :
           "every dog jogs openly" :
           "every eel inhales ably" :
           "every cat enquires ably" :
           "one antelope enquires also" :
           "every echidna adds urgently" :
           "every antelope acts anew" :
           "every echidna migrates quickly" :
           "every ant ages well" :
           "one cat dies happily" :
           "every echidna meanders also" :
           "every cat enquires urgently" :
           "every echidna eats openly" :
           "every fish runs idly" :
           "every monkey migrates happily" :
           "every elephant meanders idly" :
           "every cat observes ably" :
           "every antelope acts idly" :
           "every antelope jogs idly" :
           "every eel enquires too" :
           "every fish adds slowly" :
           "one cat ages too" :
           "every ant inhales ably" :
           "one ant ages well" :
           "one antelope acts well" :
           "every elephant observes openly" :
           "every fish arrives quickly" :
           "every fish acts frequently" :
           "every fish eats slowly" :
           "every donkey ages ably" :
           "every ant meanders then" :
           "one cat laughs easily" :
           "one dog acts also" :
           "every dog wins also" :
           "every ant arrives slowly" :
           "one ant dies openly" :
           "every cat ages slowly" :
           "one cat acts ably" :
           "every cat enquires too" :
           "every echidna laughs anew" :
           "every ox giggles too" :
           "every cat meanders quickly" :
           "every eel laughs slowly" :
           "every antelope dies already" :
           "every hamster meanders urgently" :
           "one cat runs already" :
           "every ox laughs well" :
           "one cat runs slowly" :
           "every echidna acts then" :
           "every fish giggles thus" :
           "every cat eats quickly" :
           "every echidna jogs already" :
           "every antelope adds slowly" :
           "every monkey observes frequently" :
           "one cat adds ably" :
           "every cat migrates then" :
           "every fish enquires thus" :
           "every antelope ages frequently" :
           "every eel jogs frequently" :
           "one ant runs easily" :
           "every hamster jogs thus" :
           "every antelope laughs then" :
           "one cat eats then" :
           "every donkey dies happily" :
           "every eel eats urgently" :
           "every fish arrives also" :
           "every cat arrives idly" :
           "every ant eats easily" :
           "every eel observes anew" :
           "one cat meanders happily" :
           "one antelope observes anew" :
           "every donkey observes well" :
           "every monkey runs frequently" :
           "every cat runs thus" :
           "every monkey arrives urgently" :
           "every elephant runs well" :
           "every eel dies then" :
           "one ant observes easily" :
           "every echidna wins also" :
           "every eel runs anew" :
           "one ant migrates then" :
           "every donkey enquires openly" :
           "every ant eats slowly" :
           "one ant arrives frequently" :
           "one antelope enquires too" :
           "every monkey inhales happily" :
           "every ox dies idly" :
           "one antelope acts slowly" :
           "every donkey acts frequently" :
           "one ant eats quickly" :
           "every antelope giggles quickly" :
           "every echidna ages frequently" :
           "one ant ages ably" :
           "one antelope dies also" :
           "every echidna inhales urgently" :
           "every dog inhales idly" :
           "every dog runs too" :
           "every ox adds slowly" :
           "every fish observes frequently" :
           "every antelope dies well" :
           "every echidna adds openly" :
           "one cat runs quickly" :
           "every ox runs thus" :
           "every ant observes openly" :
           "every dog eats thus" :
           "every dog arrives too" :
           "one ant observes openly" :
           "one antelope inhales slowly" :
           "every ox ages ably" :
           "every hamster meanders then" :
           "every echidna migrates easily" :
           "every hamster jogs openly" :
           "every ant adds already" :
           "one ant ages idly" :
           "every echidna eats frequently" :
           "every cat enquires quickly" :
           "every hamster meanders idly" :
           "every fish acts too" :
           "every eel jogs quickly" :
           "every ant enquires idly" :
           "every echidna arrives also" :
           "every eel inhales slowly" :
           "every elephant ages then" :
           "one antelope enquires happily" :
           "every elephant jogs anew" :
           "every cat observes well" :
           "every cat arrives too" :
           "one ant eats ably" :
           "every echidna meanders ably" :
           "every donkey laughs already" :
           "one ant eats openly" :
           "every antelope enquires frequently" :
           "every ox giggles idly" :
           "every echidna acts quickly" :
           "every eel enquires also" :
           "every cat inhales already" :
           "every antelope ages happily" :
           "every cat adds ably" :
           "one ant giggles well" :
           "every antelope runs ably" :
           "every donkey enquires slowly" :
           "every antelope arrives openly" :
           "one ant inhales quickly" :
           "every eel arrives anew" :
           "every eel migrates ably" :
           "every hamster runs frequently" :
           "every echidna eats anew" :
           "every eel laughs ably" :
           "every hamster giggles happily" :
           "every dog ages quickly" :
           "every hamster inhales openly" :
           "every dog giggles thus" :
           "every cat wins slowly" :
           "every donkey meanders then" :
           "every fish giggles idly" :
           "every monkey ages then" :
           "every echidna adds then" :
           "one antelope adds openly" :
           "every eel ages anew" :
           "one cat inhales also" :
           "one cat runs also" :
           "every fish laughs ably" :
           "every ox eats urgently" :
           "every ant adds ably" :
           "every elephant acts urgently" :
           "every donkey laughs easily" :
           "every cat acts slowly" :
           "every dog laughs happily" :
           "every hamster jogs idly" :
           "every elephant eats idly" :
           "one cat meanders well" :
           "every eel enquires thus" :
           "every ox ages then" :
           "every elephant dies then" :
           "one antelope ages thus" :
           "one ant jogs openly" :
           "every cat jogs slowly" :
           "every eel acts slowly" :
           "every ox inhales anew" :
           "every fish inhales frequently" :
           "every ant wins quickly" :
           "one ant adds then" :
           "every eel observes then" :
           "every elephant migrates then" :
           "every donkey giggles slowly" :
           "every antelope arrives easily" :
           "every fish acts quickly" :
           "every fish ages then" :
           "one cat eats easily" :
           "every eel runs easily" :
           "every ant jogs too" :
           "every dog observes then" :
           "every dog laughs openly" :
           "one antelope inhales also" :
           "every antelope giggles idly" :
           "every fish meanders openly" :
           "every monkey migrates already" :
           "every antelope arrives happily" :
           "every ant adds too" :
           "every fish dies then" :
           "every ox migrates openly" :
           "every antelope adds too" :
           "one antelope wins easily" :
           "every donkey giggles easily" :
           "every fish runs happily" :
           "every monkey migrates easily" :
           "one ant runs also" :
           "every donkey laughs ably" :
           "every eel laughs anew" :
           "one antelope meanders also" :
           "every fish acts already" :
           "every ant inhales quickly" :
           "one ant observes too" :
           "every eel wins then" :
           "every elephant enquires thus" :
           "every ant observes quickly" :
           "every cat runs well" :
           "every hamster observes anew" :
           "every monkey eats too" :
           "one ant enquires frequently" :
           "every donkey enquires frequently" :
           "every eel eats well" :
           "every echidna eats well" :
           "every antelope adds quickly" :
           "every antelope ages already" :
           "one antelope runs slowly" :
           "every donkey dies urgently" :
           "every donkey acts already" :
           "every cat acts too" :
           "one ant laughs anew" :
           "every fish dies frequently" :
           "one antelope wins openly" :
           "every eel inhales then" :
           "every elephant ages urgently" :
           "every dog laughs anew" :
           "every echidna runs too" :
           "every monkey wins slowly" :
           "every echidna adds ably" :
           "every cat dies slowly" :
           "every fish arrives urgently" :
           "every donkey ages urgently" :
           "every dog laughs already" :
           "every ant enquires ably" :
           "every echidna wins already" :
           "one cat giggles slowly" :
           "every antelope acts frequently" :
           "one antelope jogs then" :
           "every donkey jogs frequently" :
           "every monkey laughs already" :
           "every echidna inhales thus" :
           "every donkey meanders slowly" :
           "every cat ages thus" :
           "every cat meanders frequently" :
           "every antelope dies happily" :
           "one ant meanders easily" :
           "every cat eats already" :
           "one ant ages thus" :
           "every cat arrives anew" :
           "every hamster jogs also" :
           "every ox inhales happily" :
           "one cat enquires well" :
           "every antelope eats idly" :
           "every echidna observes thus" :
           "every monkey giggles happily" :
           "every echidna dies frequently" :
           "one antelope migrates anew" :
           "one ant inhales anew" :
           "every ant wins well" :
           "every monkey enquires well" :
           "every elephant ages easily" :
           "every fish laughs anew" :
           "every donkey meanders easily" :
           "every eel laughs idly" :
           "every hamster enquires ably" :
           "every ant eats already" :
           "every elephant acts too" :
           "every hamster enquires also" :
           "every cat arrives easily" :
           "every eel giggles then" :
           "every ant jogs also" :
           "one cat inhales already" :
           "every cat eats ably" :
           "one cat jogs quickly" :
           "every ox runs slowly" :
           "one antelope observes thus" :
           "every cat observes easily" :
           "every antelope observes idly" :
           "every cat observes then" :
           "every cat migrates openly" :
           "every ant acts easily" :
           "every echidna wins anew" :
           "every antelope ages ably" :
           "one cat arrives anew" :
           "every elephant wins anew" :
           "every hamster ages openly" :
           "every echidna eats quickly" :
           "every hamster arrives then" :
           "every dog jogs thus" :
           "every fish jogs idly" :
           "every antelope eats anew" :
           "every dog inhales too" :
           "one cat eats openly" :
           "every eel migrates well" :
           "every eel wins frequently" :
           "one antelope arrives slowly" :
           "one antelope meanders frequently" :
           "every echidna runs anew" :
           "every dog enquires slowly" :
           "one antelope ages already" :
           "every donkey arrives then" :
           "every fish giggles quickly" :
           "every fish jogs happily" :
           "every echidna runs already" :
           "every monkey laughs easily" :
           "one ant wins already" :
           "every donkey inhales thus" :
           "every antelope runs urgently" :
           "every ox runs ably" :
           "every hamster wins anew" :
           "every ant eats then" :
           "one antelope dies thus" :
           "every donkey giggles anew" :
           "one antelope giggles then" :
           "every ox runs well" :
           "every ox observes ably" :
           "every dog observes anew" :
           "one ant enquires too" :
           "one ant migrates urgently" :
           "one cat dies well" :
           "every elephant adds frequently" :
           "every monkey enquires ably" :
           "every echidna wins idly" :
           "every cat migrates already" :
           "every dog observes openly" :
           "every eel enquires openly" :
           "every elephant runs quickly" :
           "every monkey acts easily" :
           "every donkey arrives frequently" :
           "every eel dies openly" :
           "every echidna migrates also" :
           "every hamster giggles ably" :
           "every monkey enquires slowly" :
           "one cat migrates also" :
           "one ant acts urgently" :
           "one antelope wins already" :
           "every dog eats ably" :
           "every monkey giggles already" :
           "every ox jogs openly" :
           "every dog inhales anew" :
           "every donkey acts quickly" :
           "one cat wins frequently" :
           "every monkey laughs ably" :
           "one antelope migrates openly" :
           "every eel meanders thus" :
           "one cat laughs idly" :
           "one cat wins too" :
           "one antelope enquires already" :
           "every antelope enquires openly" :
           "every fish observes too" :
           "every donkey giggles ably" :
           "every ox laughs already" :
           "every echidna arrives already" :
           "every hamster ages slowly" :
           "every elephant inhales also" :
           "every dog laughs well" :
           "every ant enquires anew" :
           "every elephant meanders slowly" :
           "every antelope observes urgently" :
           "every ox enquires openly" :
           "every eel inhales also" :
           "one ant meanders openly" :
           "every antelope arrives also" :
           "every hamster wins easily" :
           "every hamster adds too" :
           "every donkey dies slowly" :
           "one antelope giggles urgently" :
           "every eel acts openly" :
           "every cat jogs thus" :
           "every hamster wins thus" :
           "every ox laughs ably" :
           "every dog wins too" :
           "every monkey wins too" :
           "every hamster jogs well" :
           "one antelope dies then" :
           "one cat meanders thus" :
           "every eel adds already" :
           "every ox observes well" :
           "every antelope acts happily" :
           "every elephant adds quickly" :
           "every eel meanders slowly" :
           "one cat laughs urgently" :
           "one ant meanders frequently" :
           "every echidna enquires well" :
           "every hamster inhales frequently" :
           "every antelope observes ably" :
           "one cat jogs ably" :
           "one antelope adds easily" :
           "every monkey dies anew" :
           "every echidna dies openly" :
           "every fish inhales happily" :
           "every hamster runs easily" :
           "every cat meanders also" :
           "every eel meanders already" :
           "one dog acts thus" :
           "every hamster giggles well" :
           "every ant eats happily" :
           "every hamster runs urgently" :
           "one ant jogs well" :
           "every eel runs urgently" :
           "every cat eats also" :
           "every hamster eats happily" :
           "one ant eats frequently" :
           "every ant migrates quickly" :
           "every echidna enquires idly" :
           "every dog meanders urgently" :
           "every donkey adds thus" :
           "every eel eats already" :
           "every elephant giggles well" :
           "every cat ages urgently" :
           "every donkey dies idly" :
           "every elephant acts happily" :
           "every ox enquires urgently" :
           "one cat inhales easily" :
           "every ox acts already" :
           "every hamster eats anew" :
           "every ant adds easily" :
           "every donkey laughs openly" :
           "every fish meanders happily" :
           "every cat runs slowly" :
           "every elephant laughs well" :
           "one antelope runs already" :
           "one antelope runs openly" :
           "every fish enquires already" :
           "every ant migrates idly" :
           "every cat ages anew" :
           "every cat giggles ably" :
           "every ant enquires urgently" :
           "every donkey jogs also" :
           "every ant runs openly" :
           "every elephant arrives quickly" :
           "every monkey giggles idly" :
           "every hamster arrives too" :
           "one ant inhales frequently" :
           "every cat arrives urgently" :
           "every cat arrives frequently" :
           "one ant acts openly" :
           "every hamster dies easily" :
           "every eel adds also" :
           "every cat observes also" :
           "every donkey enquires easily" :
           "every donkey eats quickly" :
           "every elephant enquires already" :
           "every fish runs also" :
           "every antelope ages too" :
           "every echidna enquires also" :
           "every cat laughs ably" :
           "every ox meanders frequently" :
           "every antelope wins then" :
           "every fish laughs slowly" :
           "every dog ages then" :
           "every echidna inhales openly" :
           "every donkey migrates happily" :
           "one ant acts ably" :
           "every ox enquires already" :
           "every fish ages ably" :
           "every donkey wins idly" :
           "one cat ages well" :
           "every fish ages urgently" :
           "every echidna dies well" :
           "every dog acts openly" :
           "every fish wins thus" :
           "every ant inhales openly" :
           "every cat acts well" :
           "one ant eats already" :
           "every cat ages also" :
           "every ant meanders openly" :
           "every hamster adds frequently" :
           "one antelope jogs thus" :
           "every cat meanders too" :
           "every eel observes frequently" :
           "every elephant runs thus" :
           "every eel ages idly" :
           "one ant migrates slowly" :
           "one antelope inhales openly" :
           "every fish enquires too" :
           "every elephant acts openly" :
           "one antelope observes well" :
           "every eel observes urgently" :
           "one ant observes then" :
           "every hamster dies urgently" :
           "every antelope adds idly" :
           "every eel dies easily" :
           "every cat giggles quickly" :
           "one ant dies already" :
           "every donkey arrives already" :
           "every antelope jogs already" :
           "every dog meanders openly" :
           "every eel arrives thus" :
           "every fish inhales also" :
           "every monkey migrates well" :
           "every eel observes well" :
           "every hamster arrives openly" :
           "every hamster acts already" :
           "every dog laughs too" :
           "every cat acts ably" :
           "every cat acts frequently" :
           "every monkey meanders slowly" :
           "every cat migrates quickly" :
           "every antelope giggles then" :
           "every ant wins also" :
           "one cat eats happily" :
           "every ox laughs anew" :
           "every ox ages frequently" :
           "one cat laughs already" :
           "every dog migrates anew" :
           "every antelope laughs anew" :
           "every antelope giggles urgently" :
           "every hamster acts then" :
           "every monkey runs anew" :
           "every dog wins then" :
           "every ox eats also" :
           "every fish observes easily" :
           "every echidna jogs idly" :
           "every cat runs quickly" :
           "one dog acts happily" :
           "one cat acts too" :
           "every dog dies quickly" :
           "one ant laughs frequently" :
           "every fish arrives well" :
           "one cat giggles also" :
           "one ant migrates thus" :
           "every antelope dies anew" :
           "every hamster wins idly" :
           "every antelope eats frequently" :
           "every ox enquires quickly" :
           "every echidna acts easily" :
           "every echidna enquires slowly" :
           "every monkey jogs then" :
           "every hamster observes easily" :
           "every ant runs slowly" :
           "every elephant acts frequently" :
           "every hamster acts slowly" :
           "one cat runs happily" :
           "every echidna enquires too" :
           "every antelope wins quickly" :
           "every antelope migrates slowly" :
           "every dog meanders already" :
           "every antelope migrates easily" :
           "one ant laughs thus" :
           "every elephant migrates happily" :
           "one antelope eats easily" :
           "every dog migrates happily" :
           "every eel laughs too" :
           "every ant laughs urgently" :
           "every fish inhales then" :
           "every monkey adds happily" :
           "every antelope wins urgently" :
           "every ant jogs idly" :
           "one antelope wins idly" :
           "one cat observes too" :
           "one ant jogs ably" :
           "every echidna inhales already" :
           "every donkey eats thus" :
           "every echidna dies already" :
           "every elephant observes quickly" :
           "every echidna arrives thus" :
           "every cat laughs easily" :
           "every dog adds too" :
           "every dog inhales urgently" :
           "every donkey inhales quickly" :
           "one ant giggles openly" :
           "every donkey eats happily" :
           "one ant wins slowly" :
           "one antelope giggles happily" :
           "every cat laughs then" :
           "every echidna dies anew" :
           "every donkey wins ably" :
           "every elephant enquires also" :
           "one cat ages slowly" :
           "every ox enquires anew" :
           "every ant laughs well" :
           "every antelope dies also" :
           "one antelope wins then" :
           "every antelope meanders happily" :
           "every cat eats then" :
           "every eel dies ably" :
           "every donkey acts urgently" :
           "every elephant adds anew" :
           "every dog adds slowly" :
           "every elephant observes slowly" :
           "every dog arrives slowly" :
           "every donkey meanders also" :
           "every donkey enquires happily" :
           "every fish eats anew" :
           "every hamster arrives well" :
           "every echidna arrives well" :
           "every fish runs then" :
           "every ant meanders already" :
           "every ox enquires also" :
           "every cat observes frequently" :
           "one antelope eats openly" :
           "every ant adds idly" :
           "every echidna wins slowly" :
           "every ox acts frequently" :
           "one ant enquires ably" :
           "every ox observes frequently" :
           "every monkey laughs happily" :
           "every donkey enquires idly" :
           "every fish laughs happily" :
           "every ant enquires happily" :
           "every echidna jogs thus" :
           "every ant arrives happily" :
           "every fish eats frequently" :
           "every echidna dies thus" :
           "every ox ages slowly" :
           "one cat observes also" :
           "every monkey inhales too" :
           "every dog jogs happily" :
           "every ox ages easily" :
           "every fish eats then" :
           "every elephant adds already" :
           "every ant ages idly" :
           "every echidna meanders then" :
           "every hamster wins already" :
           "every eel observes quickly" :
           "every donkey laughs anew" :
           "every dog wins openly" :
           "every elephant observes frequently" :
           "every dog jogs ably" :
           "every echidna adds already" :
           "every fish meanders frequently" :
           "every echidna arrives happily" :
           "every donkey migrates too" :
           "every cat dies ably" :
           "one antelope meanders already" :
           "every eel eats easily" :
           "one ant jogs slowly" :
           "every antelope observes frequently" :
           "every ox giggles quickly" :
           "every echidna acts openly" :
           "one cat giggles quickly" :
           "every ant migrates ably" :
           "every ant arrives thus" :
           "every donkey migrates already" :
           "every ox observes openly" :
           "every antelope dies frequently" :
           "every fish wins ably" :
           "every fish runs already" :
           "every hamster jogs slowly" :
           "every hamster giggles anew" :
           "one cat observes well" :
           "one ant eats too" :
           "every cat giggles easily" :
           "every fish ages quickly" :
           "every hamster ages thus" :
           "every elephant enquires easily" :
           "every cat laughs openly" :
           "every hamster laughs easily" :
           "one cat laughs well" :
           "every antelope acts urgently" :
           "every donkey jogs slowly" :
           "every cat wins anew" :
           "every cat meanders thus" :
           "one ant runs urgently" :
           "every antelope adds thus" :
           "one dog adds already" :
           "every ox eats easily" :
           "every monkey jogs too" :
           "one ant acts thus" :
           "every hamster adds also" :
           "every donkey wins already" :
           "every hamster arrives idly" :
           "every fish giggles also" :
           "every fish acts urgently" :
           "every ant dies anew" :
           "one antelope arrives frequently" :
           "every ox giggles also" :
           "every antelope dies easily" :
           "every elephant arrives also" :
           "every dog jogs frequently" :
           "every fish arrives openly" :
           "every cat eats happily" :
           "every ox runs quickly" :
           "one antelope acts idly" :
           "every ant enquires already" :
           "every fish enquires easily" :
           "every fish runs thus" :
           "every ox eats already" :
           "every cat dies well" :
           "one antelope enquires then" :
           "every monkey acts ably" :
           "every eel giggles slowly" :
           "every elephant meanders ably" :
           "every donkey ages anew" :
           "every fish giggles ably" :
           "every echidna enquires then" :
           "every antelope laughs frequently" :
           "every hamster acts frequently" :
           "every ant migrates slowly" :
           "every fish wins too" :
           "every dog giggles happily" :
           "every dog acts also" :
           "every elephant migrates quickly" :
           "every hamster dies thus" :
           "one antelope runs frequently" :
           "every monkey giggles also" :
           "one antelope laughs then" :
           "every ox enquires thus" :
           "every ant observes anew" :
           "every hamster jogs anew" :
           "every echidna arrives slowly" :
           "every dog meanders anew" :
           "one antelope giggles quickly" :
           "every donkey observes too" :
           "one ant meanders anew" :
           "every antelope dies then" :
           "one cat jogs too" :
           "one antelope meanders anew" :
           "every dog observes too" :
           "every eel arrives too" :
           "every antelope arrives slowly" :
           "one antelope wins frequently" :
           "every eel ages urgently" :
           "every monkey observes too" :
           "every ox dies openly" :
           "every monkey wins thus" :
           "every dog enquires well" :
           "every cat eats frequently" :
           "every donkey wins happily" :
           "every elephant runs frequently" :
           "one cat giggles then" :
           "one antelope ages frequently" :
           "every cat wins urgently" :
           "every antelope ages easily" :
           "every antelope jogs then" :
           "one ant meanders also" :
           "one cat jogs urgently" :
           "every echidna acts also" :
           "every antelope eats well" :
           "every cat laughs thus" :
           "every antelope enquires idly" :
           "every dog jogs slowly" :
           "every monkey migrates thus" :
           "one antelope meanders easily" :
           "every cat meanders slowly" :
           "every dog acts too" :
           "every donkey runs openly" :
           "every donkey migrates thus" :
           "every ant migrates also" :
           "every dog ages anew" :
           "one antelope acts too" :
           "every ox arrives frequently" :
           "every hamster adds ably" :
           "one antelope dies quickly" :
           "every dog inhales already" :
           "one antelope wins also" :
           "every dog inhales quickly" :
           "every monkey runs ably" :
           "every eel ages then" :
           "one cat inhales happily" :
           "one antelope giggles ably" :
           "every cat giggles already" :
           "one ant arrives quickly" :
           "one cat runs too" :
           "every echidna observes openly" :
           "every fish observes anew" :
           "every hamster observes ably" :
           "every fish arrives idly" :
           "every ant jogs already" :
           "one cat laughs anew" :
           "every cat meanders anew" :
           "every dog giggles quickly" :
           "every ox adds then" :
           "every antelope observes well" :
           "every cat laughs frequently" :
           "every echidna laughs easily" :
           "every dog laughs easily" :
           "every ant migrates well" :
           "one antelope eats too" :
           "every donkey meanders urgently" :
           "every hamster giggles easily" :
           "every elephant eats happily" :
           "every dog dies anew" :
           "every echidna arrives easily" :
           "every elephant meanders happily" :
           "every hamster wins too" :
           "one cat meanders openly" :
           "every echidna runs also" :
           "every monkey eats openly" :
           "every dog meanders too" :
           "every fish wins idly" :
           "every fish eats ably" :
           "every ant giggles urgently" :
           "every donkey runs urgently" :
           "one cat jogs openly" :
           "every fish eats urgently" :
           "one antelope dies too" :
           "every ox observes anew" :
           "one antelope jogs anew" :
           "every fish adds quickly" :
           "every dog inhales happily" :
           "every eel enquires anew" :
           "every eel dies urgently" :
           "every eel adds idly" :
           "every eel jogs anew" :
           "every hamster dies too" :
           "every ox giggles then" :
           "every cat inhales slowly" :
           "every eel inhales happily" :
           "every monkey meanders then" :
           "every monkey eats frequently" :
           "every ox runs idly" :
           "one dog acts urgently" :
           "every monkey inhales ably" :
           "every hamster migrates quickly" :
           "every cat jogs idly" :
           "one cat eats thus" :
           "every eel jogs easily" :
           "every elephant ages too" :
           "every elephant jogs well" :
           "every cat jogs openly" :
           "every antelope migrates already" :
           "every donkey giggles also" :
           "one antelope acts then" :
           "one ant ages too" :
           "every monkey migrates anew" :
           "every echidna migrates happily" :
           "every ox eats anew" :
           "one cat meanders already" :
           "every donkey observes thus" :
           "every eel dies thus" :
           "every ox acts also" :
           "one cat runs frequently" :
           "every monkey observes then" :
           "one cat adds too" :
           "one dog acts slowly" :
           "one cat enquires frequently" :
           "every hamster laughs already" :
           "every ant jogs easily" :
           "one antelope acts frequently" :
           "one cat eats ably" :
           "one ant arrives well" :
           "one antelope adds happily" :
           "every eel giggles too" :
           "every antelope wins ably" :
           "every eel enquires well" :
           "every elephant enquires anew" :
           "every cat adds happily" :
           "every ant meanders slowly" :
           "every cat dies also" :
           "one cat arrives urgently" :
           "every cat eats easily" :
           "every eel eats happily" :
           "one ant adds happily" :
           "one antelope acts ably" :
           "every dog adds quickly" :
           "every hamster migrates anew" :
           "every ant ages anew" :
           "one cat meanders easily" :
           "every fish acts ably" :
           "every hamster giggles slowly" :
           "every echidna migrates anew" :
           "every elephant jogs ably" :
           "every donkey eats well" :
           "every antelope enquires slowly" :
           "every cat migrates happily" :
           "one cat migrates urgently" :
           "every donkey dies anew" :
           "every echidna wins frequently" :
           "one cat observes happily" :
           "every fish enquires urgently" :
           "every monkey adds slowly" :
           "every eel dies idly" :
           "one antelope dies slowly" :
           "one antelope observes slowly" :
           "every dog giggles well" :
           "every eel meanders quickly" :
           "every cat arrives ably" :
           "every ant eats openly" :
           "one cat wins also" :
           "every fish arrives slowly" :
           "every fish jogs thus" :
           "one ant ages quickly" :
           "every fish wins openly" :
           "every echidna giggles already" :
           "every cat wins frequently" :
           "every antelope dies thus" :
           "every antelope acts then" :
           "every eel eats thus" :
           "one cat eats frequently" :
           "one cat observes easily" :
           "every cat dies already" :
           "every eel giggles happily" :
           "every elephant arrives too" :
           "one cat laughs happily" :
           "every echidna ages slowly" :
           "every fish jogs also" :
           "every echidna meanders too" :
           "one cat jogs frequently" :
           "every donkey arrives openly" :
           "every monkey laughs well" :
           "every eel laughs also" :
           "every antelope migrates then" :
           "every antelope enquires then" :
           "every monkey dies ably" :
           "every ox giggles openly" :
           "every ox migrates too" :
           "every echidna laughs also" :
           "one ant meanders ably" :
           "every dog giggles anew" :
           "every ox arrives idly" :
           "every ox jogs quickly" :
           "every monkey laughs also" :
           "one cat acts well" :
           "every elephant arrives slowly" :
           "every ox laughs frequently" :
           "every antelope inhales too" :
           "every monkey wins idly" :
           "one ant wins urgently" :
           "every cat laughs anew" :
           "one cat jogs also" :
           "every dog runs urgently" :
           "every antelope acts thus" :
           "every ox dies also" :
           "every dog runs slowly" :
           "every monkey migrates frequently" :
           "every dog enquires quickly" :
           "every antelope dies too" :
           "every ant observes well" :
           "one antelope giggles also" :
           "every fish meanders slowly" :
           "every ant wins urgently" :
           "every echidna laughs urgently" :
           "every fish wins already" :
           "every echidna adds idly" :
           "one ant arrives urgently" :
           "every echidna migrates then" :
           "every monkey meanders easily" :
           "every elephant inhales then" :
           "every ox laughs easily" :
           "every ox enquires idly" :
           "every antelope wins happily" :
           "every eel arrives frequently" :
           "one ant observes also" :
           "one antelope dies ably" :
           "every ox acts well" :
           "every elephant arrives thus" :
           "every echidna meanders well" :
           "every fish acts idly" :
           "every eel enquires frequently" :
           "every eel meanders also" :
           "every dog ages also" :
           "one antelope eats slowly" :
           "every monkey adds quickly" :
           "every ox giggles anew" :
           "every eel jogs then" :
           "one ant runs openly" :
           "every cat acts quickly" :
           "every monkey jogs also" :
           "every antelope inhales well" :
           "one cat runs idly" :
           "every ox jogs easily" :
           "every fish dies urgently" :
           "every hamster laughs well" :
           "every ox arrives anew" :
           "every cat enquires thus" :
           "every dog runs idly" :
           "every dog acts idly" :
           "every ant giggles already" :
           "every cat enquires then" :
           "every ox acts quickly" :
           "every dog runs already" :
           "every cat giggles then" :
           "one cat laughs also" :
           "every dog jogs then" :
           "one antelope runs ably" :
           "every ant eats well" :
           "every donkey meanders happily" :
           "every donkey wins also" :
           "one ant inhales easily" :
           "every ox arrives openly" :
           "every elephant jogs openly" :
           "every echidna wins ably" :
           "every fish giggles already" :
           "every antelope arrives anew" :
           "every antelope giggles anew" :
           "every ant migrates then" :
           "every eel ages quickly" :
           "every ox adds anew" :
           "every hamster dies already" :
           "every dog ages too" :
           "every eel laughs well" :
           "every fish runs urgently" :
           "every antelope adds openly" :
           "one antelope inhales then" :
           "every eel arrives happily" :
           "every dog arrives already" :
           "every antelope enquires urgently" :
           "every monkey adds already" :
           "every donkey arrives anew" :
           "one cat wins thus" :
           "every donkey inhales slowly" :
           "every eel inhales frequently" :
           "every donkey acts thus" :
           "every eel migrates openly" :
           "every antelope inhales urgently" :
           "every echidna wins happily" :
           "every cat meanders ably" :
           "every monkey runs happily" :
           "every ox wins slowly" :
           "one ant enquires openly" :
           "every ox migrates anew" :
           "every cat giggles openly" :
           "every hamster jogs quickly" :
           "every fish enquires then" :
           "one cat eats urgently" :
           "one dog acts easily" :
           "one cat acts happily" :
           "every elephant acts quickly" :
           "every antelope runs happily" :
           "every cat laughs also" :
           "every echidna jogs quickly" :
           "every monkey inhales also" :
           "every hamster migrates well" :
           "one ant laughs also" :
           "every echidna enquires happily" :
           "every antelope eats thus" :
           "one cat wins happily" :
           "one ant ages easily" :
           "one cat enquires already" :
           "every hamster migrates frequently" :
           "every elephant migrates also" :
           "one cat ages also" :
           "every echidna observes frequently" :
           "every fish ages frequently" :
           "every ant arrives urgently" :
           "one ant giggles idly" :
           "every cat arrives openly" :
           "every echidna acts slowly" :
           "every dog eats quickly" :
           "every cat eats thus" :
           "every elephant eats easily" :
           "every donkey laughs idly" :
           "one antelope laughs well" :
           "every donkey inhales urgently" :
           "one cat adds quickly" :
           "one ant jogs easily" :
           "every eel dies frequently" :
           "one ant eats well" :
           "every ox eats thus" :
           "every ant observes slowly" :
           "every ox migrates quickly" :
           "every fish ages easily" :
           "every ox jogs well" :
           "every elephant migrates easily" :
           "every monkey adds then" :
           "every elephant adds happily" :
           "every dog enquires also" :
           "every dog wins ably" :
           "every donkey jogs then" :
           "one antelope eats happily" :
           "one cat runs ably" :
           "every ox migrates ably" :
           "every elephant giggles quickly" :
           "every dog dies also" :
           "every hamster observes well" :
           "every cat wins already" :
           "every donkey laughs too" :
           "one cat meanders too" :
           "every hamster dies anew" :
           "every antelope observes easily" :
           "every elephant jogs thus" :
           "every eel eats then" :
           "one antelope laughs too" :
           "one ant enquires urgently" :
           "every hamster inhales too" :
           "every hamster laughs openly" :
           "every elephant adds then" :
           "every eel laughs easily" :
           "one antelope enquires ably" :
           "every fish laughs also" :
           "every eel jogs happily" :
           "every fish ages anew" :
           "one cat runs easily" :
           "every monkey wins quickly" :
           "one antelope wins slowly" :
           "every fish dies already" :
           "every fish acts also" :
           "one cat migrates anew" :
           "every echidna jogs frequently" :
           "every cat migrates anew" :
           "every hamster observes then" :
           "every echidna jogs too" :
           "every cat laughs idly" :
           "one ant adds also" :
           "one cat meanders quickly" :
           "every eel acts then" :
           "one ant laughs quickly" :
           "every eel dies quickly" :
           "every fish ages thus" :
           "every hamster dies ably" :
           "one ant adds urgently" :
           "every ant jogs then" :
           "every echidna jogs well" :
           "every cat runs ably" :
           "one antelope dies urgently" :
           "every monkey dies too" :
           "every ox giggles already" :
           "every elephant ages idly" :
           "every ant acts ably" :
           "every hamster observes frequently" :
           "every hamster laughs ably" :
           "every echidna eats also" :
           "every fish observes quickly" :
           "every echidna adds frequently" :
           "every ox eats quickly" :
           "every elephant observes idly" :
           "every ant dies then" :
           "every ox ages happily" :
           "every echidna jogs also" :
           "every hamster enquires openly" :
           "every hamster laughs too" :
           "every ant inhales also" :
           "every monkey wins happily" :
           "one antelope dies well" :
           "one antelope laughs thus" :
           "one antelope arrives anew" :
           "one antelope runs easily" :
           "every fish adds then" :
           "every monkey jogs frequently" :
           "every ox migrates slowly" :
           "every monkey observes idly" :
           "every fish laughs well" :
           "every ant ages too" :
           "every cat adds thus" :
           "one cat acts also" :
           "every antelope wins well" :
           "every cat laughs well" :
           "every ant migrates anew" :
           "every echidna acts already" :
           "every ant migrates too" :
           "one ant giggles already" :
           "every antelope inhales quickly" :
           "every monkey inhales openly" :
           "every donkey inhales too" :
           "one cat giggles happily" :
           "every echidna observes ably" :
           "every hamster migrates idly" :
           "every hamster ages idly" :
           "every monkey wins easily" :
           "every fish inhales thus" :
           "every donkey dies well" :
           "every echidna enquires quickly" :
           "every eel inhales already" :
           "one ant wins thus" :
           "one antelope jogs too" :
           "every echidna dies slowly" :
           []
